### ISSUE TITLE
TestStandaloneOrientDBCompatibility fails " Error on parsing query at position #6: Error on parsing query"

### ISSUE THREAD

**Issue by krichter722** [PhantomYdn/wicket-orientdb#23]
Running ru.ydn.wicket.wicketorientdb.orientdb.TestStandaloneOrientDBCompatibility
    Apr 04, 2015 2:49:34 AM com.orientechnologies.common.log.OLogManager log
    INFORMATION: OrientDB auto-config DISKCACHE=10.320MB (heap=3.534MB os=15.903MB disk=19.715MB)

    2015-04-04 02:49:34:943 INFO  Loading configuration from input stream [OServerConfigurationLoaderXml]
    2015-04-04 02:49:35:058 INFO  OrientDB Server v2.0.6 is starting up... [OServer]
    2015-04-04 02:49:35:073 INFO  Databases directory: /mnt/DATA/sources/Orienteer/wicket-orientdb/wicket-orientdb/./databases [OServer]
    2015-04-04 02:49:35:092 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.28, socket=default) [OServerNetworkListener]
    2015-04-04 02:49:35:093 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
    2015-04-04 02:49:35:095 INFO  OrientDB Server v2.0.6 is active. [OServer]
    2015-04-04 02:49:38:662 INFO  {db=testDBLifeCycle} Loading configuration from input stream [OServerConfigurationLoaderXml]
    2015-04-04 02:49:38:695 INFO  {db=testDBLifeCycle} OrientDB Server v2.0.6 is starting up... [OServer]
    2015-04-04 02:49:38:695 INFO  {db=testDBLifeCycle} Databases directory: /mnt/DATA/sources/Orienteer/wicket-orientdb/wicket-orientdb/./databases [OServer]
    2015-04-04 02:49:38:696 INFO  {db=testDBLifeCycle} Port 0.0.0.0:2424 busy, trying the next available... [OServerNetworkListener]
    2015-04-04 02:49:38:696 INFO  {db=testDBLifeCycle} Listening binary connections on 0.0.0.0:2425 (protocol v.28, socket=default) [OServerNetworkListener]
    2015-04-04 02:49:38:697 INFO  {db=testDBLifeCycle} Port 0.0.0.0:2480 busy, trying the next available... [OServerNetworkListener]
    2015-04-04 02:49:38:697 INFO  {db=testDBLifeCycle} Listening http connections on 0.0.0.0:2481 (protocol v.10, socket=default) [OServerNetworkListener]
    2015-04-04 02:49:38:698 INFO  {db=testDBLifeCycle} OrientDB Server v2.0.6 is active. [OServer]
    2015-04-04 02:49:38:964 INFO  OrientDB Server is shutting down... [OServer]
    2015-04-04 02:49:38:965 INFO  Shutting down listeners: [OServer]
    2015-04-04 02:49:38:965 INFO  - ONetworkProtocolBinary /0.0.0.0:2425: [OServer]
    2015-04-04 02:49:38:965 INFO  - ONetworkProtocolHttpDb /0.0.0.0:2481: [OServer]
    2015-04-04 02:49:38:966 INFO  Shutting down protocols [OServer]
    2015-04-04 02:49:38:966 INFO  Shutting down plugins: [OServerPluginManager]
    2015-04-04 02:49:38:968 INFO  Shutting down databases: [OServer]
    2015-04-04 02:49:38:969 INFO  - closing storage: testDBOpen... [Orient]
    2015-04-04 02:49:38:970 INFO  - closing storage: testDBLifeCycle... [Orient]
    2015-04-04 02:49:43:112 INFO  OrientDB Engine shutdown complete [Orient]
    2015-04-04 02:49:43:113 INFO  OrientDB Server shutdown complete [OServer]
    2015-04-04 02:49:43:116 INFO  Loading configuration from input stream [OServerConfigurationLoaderXml]
    2015-04-04 02:49:43:145 INFO  OrientDB Server v2.0.6 is starting up... [OServer]
    2015-04-04 02:49:43:146 INFO  Databases directory: /mnt/DATA/sources/Orienteer/wicket-orientdb/wicket-orientdb/./databases [OServer]
    2015-04-04 02:49:43:146 INFO  Port 0.0.0.0:2424 busy, trying the next available... [OServerNetworkListener]
    2015-04-04 02:49:43:146 INFO  Listening binary connections on 0.0.0.0:2425 (protocol v.28, socket=default) [OServerNetworkListener]
    2015-04-04 02:49:43:147 INFO  Port 0.0.0.0:2480 busy, trying the next available... [OServerNetworkListener]
    2015-04-04 02:49:43:147 INFO  Listening http connections on 0.0.0.0:2481 (protocol v.10, socket=default) [OServerNetworkListener]
    2015-04-04 02:49:43:147 INFO  OrientDB Server v2.0.6 is active. [OServer]
    2015-04-04 02:49:43:285 INFO  OrientDB Server is shutting down... [OServer]
    2015-04-04 02:49:43:285 INFO  Shutting down listeners: [OServer]
    2015-04-04 02:49:43:286 INFO  - ONetworkProtocolBinary /0.0.0.0:2425: [OServer]
    2015-04-04 02:49:43:286 INFO  - ONetworkProtocolHttpDb /0.0.0.0:2481: [OServer]
    2015-04-04 02:49:43:286 INFO  Shutting down protocols [OServer]
    2015-04-04 02:49:43:287 INFO  Shutting down plugins: [OServerPluginManager]
    2015-04-04 02:49:43:287 INFO  Shutting down databases: [OServer]
    2015-04-04 02:49:43:287 INFO  - closing storage: testDBOpen... [Orient]
    2015-04-04 02:49:43:288 INFO  OrientDB Engine shutdown complete [Orient]
    2015-04-04 02:49:43:289 INFO  OrientDB Server shutdown complete [OServer]Tests run: 5, Failures: 0, Errors: 1, Skipped: 3, Time elapsed: 8.965 sec <<< FAILURE!

    2015-04-04 02:49:43:298 INFO  OrientDB Server is shutting down... [OServer]
    Results :

    Tests in error: 
      testPLocalDbLifeCycle(ru.ydn.wicket.wicketorientdb.orientdb.TestStandaloneOrientDBCompatibility): Error on parsing query at position #6: Error on parsing query

    Tests run: 5, Failures: 0, Errors: 1, Skipped: 3

experienced with 66e1016801ff6fad9e78bbde35c73a560fe64dad (passes on travis, but I could reproduce this 100 % of the 4 times I tried).

**Comment by PhantomYdn** [comment]
What JDK are you using? And can you please post full stacktrace.

Btw, package ru.ydn.wicket.wicketorientdb.orientdb contains testcases for OrientDB themself. So if something failed - it failed in OrientDB. But before posting issue to OrientDB - let's try to figure out what's going on...

**Comment by krichter722** [comment]
Stacktrace is

    Error on parsing query at position #6: Error on parsing query Query:  OUser where name = 'admin' limit 1 -----------^
    com.orientechnologies.orient.core.exception.OQueryParsingException
    Query:  OUser where name = 'admin' limit 1
    -----------^
	    at com.orientechnologies.orient.core.sql.filter.OSQLTarget.<init>(OSQLTarget.java:76)
	    at com.orientechnologies.orient.core.sql.OSQLEngine.parseTarget(OSQLEngine.java:440)
	    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:218)
	    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:96)
	    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:56)
	    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:37)
	    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1176)
	    at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
	    at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	    at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	    at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:490)
	    at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:215)
	    at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:169)
	    at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:87)
	    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:260)
	    at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:285)
	    at ru.ydn.wicket.wicketorientdb.orientdb.TestStandaloneOrientDBCompatibility.testOrientDbLifeCycle(TestStandaloneOrientDBCompatibility.java:145)
	    at ru.ydn.wicket.wicketorientdb.orientdb.TestStandaloneOrientDBCompatibility.testPLocalDbLifeCycle(TestStandaloneOrientDBCompatibility.java:89)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:497)
	    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:497)
	    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
    Caused by: com.orientechnologies.orient.core.exception.OCommandExecutionException: Class 'OUSER' was not found in current database
	    at com.orientechnologies.orient.core.sql.filter.OSQLTarget.extractTargets(OSQLTarget.java:262)
	    at com.orientechnologies.orient.core.sql.filter.OSQLTarget.<init>(OSQLTarget.java:67)
	    ... 46 more

JDK is `OpenJDK` 1.8.0_40-internal; OpenJDK 64-Bit Server VM 25.40-b25

**Comment by PhantomYdn** [comment]
Very strange... OUSER should be create automatically, but exception is telling that DB doesn't have OUSER.

If you just start Orienteer over this DB: is it running good?

**Comment by krichter722** [comment]
I didn't manage to start Orienteer yet. I'm about to fix some issues in order to facilitate debugging there, but does `wicket-orientdb` depend on `Orienteer` (and the other way around)?

**Comment by PhantomYdn** [comment]
Orieteer depends on wicket-orientdb. I'm just guess: might be normal start of DB can fix schema.

Hmmm... just understand that wicket-orientdb is using in memory DB for tests. Can you try with JDK 7?

**Comment by krichter722** [comment]
same result; as well as with 4751f535fa2446ffca86fb82be8ec052b26947bd

**Comment by krichter722** [comment]
There seems to be an issue with failing shutdown hooks, see chat at https://gitter.im/PhantomYdn/Orienteer# for details

**Comment by PhantomYdn** [comment]
How is this bug? Have you still experiencing it?

**Comment by krichter722** [comment]
Thanks for reminding me. No, I think it was due to a corrupted local database which I deleted (the directory for storage). I'll reopen if it happens again.
